"""RepoLearn portable human-learning contracts."""

from .assessment import (
    AssessmentClassification,
    AssessmentResult,
    CueLevel,
    EvidenceProvenance,
    EvidenceTiming,
    JudgmentEvidence,
    MasteryLevel,
    TransferDistance,
    assess_judgment,
)
from .backends import (
    BackendConflictError,
    LocalFileBackend,
    NexusLedgerBackend,
    ProjectionConflictError,
    ReadOnlyCanonicalBackendError,
    StaleProjectionError,
)
from .client import (
    ClientLearningDecision,
    LearningResponseDisposition,
    LearningResponseResult,
    classify_learning_response,
    prepare_learning_decision,
)
from .interaction import (
    GuidedBranch,
    InteractionDefect,
    InteractionObservationReceipt,
    PromptDeliveryObservation,
    ResponseRelevance,
    UserJudgmentSignal,
    select_guided_branch,
)
from .state import StateBackend, StateUnavailableError
from .triggers import (
    ActivationSource,
    InteractionMode,
    LearningOpportunity,
    TaskContext,
    TriggerDisposition,
    TriggerResult,
    select_learning_opportunity,
)

__all__ = [
    "ActivationSource",
    "AssessmentClassification",
    "AssessmentResult",
    "BackendConflictError",
    "ClientLearningDecision",
    "CueLevel",
    "EvidenceProvenance",
    "EvidenceTiming",
    "GuidedBranch",
    "InteractionDefect",
    "InteractionMode",
    "InteractionObservationReceipt",
    "JudgmentEvidence",
    "LearningOpportunity",
    "LearningResponseDisposition",
    "LearningResponseResult",
    "LocalFileBackend",
    "MasteryLevel",
    "NexusLedgerBackend",
    "ProjectionConflictError",
    "PromptDeliveryObservation",
    "ReadOnlyCanonicalBackendError",
    "ResponseRelevance",
    "StaleProjectionError",
    "StateBackend",
    "StateUnavailableError",
    "TaskContext",
    "TransferDistance",
    "TriggerDisposition",
    "TriggerResult",
    "UserJudgmentSignal",
    "assess_judgment",
    "classify_learning_response",
    "prepare_learning_decision",
    "select_guided_branch",
    "select_learning_opportunity",
]
