"""RepoLearn portable human-learning contracts."""

from .assessment import (
    AssessmentClassification,
    AssessmentResult,
    CueLevel,
    EvidenceProvenance,
    EvidenceTiming,
    JudgmentEvidence,
    MasteryLevel,
    TransferDistance,
    assess_judgment,
)
from .backends import (
    BackendConflictError,
    LocalFileBackend,
    NexusLedgerBackend,
    ProjectionConflictError,
    ReadOnlyCanonicalBackendError,
    StaleProjectionError,
)
from .client import (
    ClientLearningDecision,
    LearningResponseDisposition,
    LearningResponseResult,
    classify_learning_response,
    prepare_learning_decision,
)
from .cue_policy import (
    AttemptIndependence,
    FADING_VALIDITY_DAYS,
    MIN_FADING_DELAY_HOURS,
    FadingDecision,
    derive_fading_decision,
    fading_is_current,
)
from .host_eval import compute_skill_content_sha256, hash_user_visible_trace
from .interaction import (
    EvaluationSource,
    GuidedBranch,
    InteractionDefect,
    InteractionObservationReceipt,
    PromptDeliveryObservation,
    ResponseRelevance,
    UserJudgmentSignal,
    select_guided_branch,
)
from .state import StateBackend, StateUnavailableError
from .triggers import (
    ActivationSource,
    InteractionMode,
    LearningOpportunity,
    TaskContext,
    TriggerDisposition,
    TriggerResult,
    select_learning_opportunity,
)
from .version import CONTRACT_CONTROL_FILES, CONTRACT_REVISION

__all__ = [
    "ActivationSource",
    "AssessmentClassification",
    "AssessmentResult",
    "AttemptIndependence",
    "BackendConflictError",
    "CONTRACT_CONTROL_FILES",
    "CONTRACT_REVISION",
    "ClientLearningDecision",
    "CueLevel",
    "EvaluationSource",
    "EvidenceProvenance",
    "EvidenceTiming",
    "FADING_VALIDITY_DAYS",
    "MIN_FADING_DELAY_HOURS",
    "FadingDecision",
    "GuidedBranch",
    "InteractionDefect",
    "InteractionMode",
    "InteractionObservationReceipt",
    "JudgmentEvidence",
    "LearningOpportunity",
    "LearningResponseDisposition",
    "LearningResponseResult",
    "LocalFileBackend",
    "MasteryLevel",
    "NexusLedgerBackend",
    "ProjectionConflictError",
    "PromptDeliveryObservation",
    "ReadOnlyCanonicalBackendError",
    "ResponseRelevance",
    "StaleProjectionError",
    "StateBackend",
    "StateUnavailableError",
    "TaskContext",
    "TransferDistance",
    "TriggerDisposition",
    "TriggerResult",
    "UserJudgmentSignal",
    "assess_judgment",
    "classify_learning_response",
    "compute_skill_content_sha256",
    "derive_fading_decision",
    "fading_is_current",
    "hash_user_visible_trace",
    "prepare_learning_decision",
    "select_guided_branch",
    "select_learning_opportunity",
]
